version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app_network
    # Uncomment below if you want to depend on a local MongoDB service
    # depends_on:
    #   - mongo

  # Uncomment this section to run MongoDB locally for development
  # mongo:
  #   image: mongo:6
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mngadmin
  #     MONGO_INITDB_ROOT_PASSWORD: yourpassword
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge