# docker-compose.prod.yml

services:
  app: 
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    environment:
      # Similar to staging, it relies on the MONGO_ATLAS_URI from the main env.
      DEBUG_MODE: "false"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"